package com.company.enums;

public enum AdminStatus {
    ADD_SUBJECT_NAME,
    GET_FILE_BY_SUBJECT_ID,
    ADD_QUESTION_BY_SUBJECT_ID,
    EDIT_SUBJECT_NAME,
    DELETE_SUBJECT,
    ADD_ADMIN,
    ADD_QUESTION_CORRECT_ANSWER,
    ADD_QUESTION_TITLE,
    ADD_QUESTION_WRONG_ANSWERS,

     DELETE_QUESTION,
    SHARE_ADVERT,
    DELETE_ADMIN,
}
